name: Generate Progress Image

on:
  push:
    branches:
      - main

jobs:
  update-progress:
    if: github.repository == 'GRAnimated/MinecraftLCE-docs'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PROGRESS_REPO_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install Pillow datetime
        
      - name: Generate progress image
        run: python scripts/generate-image.py

      - name: Commit and push changes
        run: |
          git config --global user.name "Update progress workflow"
          git config --global user.email "actions@github.com"
          git add img/progress.png
          git commit -m "Update progress img"
          git push origin main
